version: '3'

services:
  chatin-prod:
    image: frchandra/chatin-be:${DOCKER_TAG}
    container_name: chatin_be_prod
    volumes:
      - ~/infra/vault/.env:/chatin/.env:ro
      - ~/infra/vault/senpro-381803-cffcf39a0935.json:/chatin/senpro-381803-cffcf39a0935.json:ro
      - ~/infra/vault/storage:/chatin/storage
    ports:
      - "127.0.0.1:5001:5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatin-be-prod-http.rule=Host(`senpro-api.bekisar.net`)"
      - "traefik.http.routers.chatin-be-prod-http.entrypoints=web"
      - "traefik.http.routers.chatin-be-prod-http.middlewares=redirect-to-https@docker"
      - "traefik.http.routers.chatin-be-prod-http.service=noop@internal"
      - "traefik.http.routers.chatin-be-prod-https.rule=Host(`senpro-api.bekisar.net`)"
      - "traefik.http.routers.chatin-be-prod-https.entrypoints=websecure"
      - "traefik.http.routers.chatin-be-prod-https.tls=true"
      - "traefik.http.routers.chatin-be-prod-https.tls.certresolver=letsencrypt"
    networks:
      - gateway_ingress
    read_only: true

networks:
  gateway_ingress:
    external: true