version: '3.7'

services:
  app:
    container_name: chatin-app
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: app
    volumes:
      - ./.env:/chatin/.env
      - ./senpro-381803-cffcf39a0935.json:/chatin/senpro-381803-cffcf39a0935.json
    ports:
      - "8080:8080"
    networks:
      - chatin-network
    depends_on:
      - db
      - cache
    restart: unless-stopped

  db:
    image: 'mongo:6.0-jammy'
    container_name: chatin-db
    ports:
      - "27017:${DB_PORT:-27017}"
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-root}
    volumes:
      - chatin-mongo-data:/data/db
      - ./database/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    networks:
      - chatin-network

  cache:
    container_name: chatin-cache
    image: redis:7.0-bullseye
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning --requirepass ${REDIS_PASSWORD:-root}
    networks:
      - chatin-network

networks:
  chatin-network:
    driver: bridge

volumes:
  chatin-mongo-data:
    driver: local
