name: Docker Image CI Production

on:
  push:
    branches:
      - master
      - main
jobs:
  build-prod:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag frchandra/chatin-be:$(git rev-parse --short HEAD)
      - name: Push to DockerHub
        run: docker login -u ${{ secrets.DH_USER }} -p ${{ secrets.DH_PASS }} && docker push frchandra/chatin-be:$(git rev-parse --short HEAD)

  deploy-prod:
    runs-on: self-hosted
    needs: build-prod
    steps:
      - name: Run Docker Container
        run: export DOCKER_TAG=$(git rev-parse --short HEAD) && cp ~/infra/vault/.env.production .env && docker compose -f docker-compose.prod.yml up -d